// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFvtITztefK5BhufyfQ912nGz2NYXSC5U',
    appId: '1:736662249681:web:5c63d283b5d83cadae65f0',
    messagingSenderId: '736662249681',
    projectId: 'lampy-ad5ce',
    authDomain: 'lampy-ad5ce.firebaseapp.com',
    storageBucket: 'lampy-ad5ce.appspot.com',
    measurementId: 'G-EVGMBGBX5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI56EICHhxhXLd4yXkLeo6N1IogcVlb68',
    appId: '1:736662249681:android:6da2f930f8e60268ae65f0',
    messagingSenderId: '736662249681',
    projectId: 'lampy-ad5ce',
    storageBucket: 'lampy-ad5ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy4a-81WIEbV0YKaZqF_x-aa6nJtpvZuM',
    appId: '1:736662249681:ios:361c34c65c59a695ae65f0',
    messagingSenderId: '736662249681',
    projectId: 'lampy-ad5ce',
    storageBucket: 'lampy-ad5ce.appspot.com',
    iosBundleId: 'com.example.lampy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy4a-81WIEbV0YKaZqF_x-aa6nJtpvZuM',
    appId: '1:736662249681:ios:361c34c65c59a695ae65f0',
    messagingSenderId: '736662249681',
    projectId: 'lampy-ad5ce',
    storageBucket: 'lampy-ad5ce.appspot.com',
    iosBundleId: 'com.example.lampy',
  );
}
